package main

import "strings"

func GenerateFirefoxBookmarks(bookmarks Bookmarks) string {
	var builder strings.Builder

	builder.WriteString("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n")
	builder.WriteString("<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self'; script-src 'none'; img-src data: *; object-src 'none'\">\n")

	builder.WriteString("<title>Generated Bookmarks</title>\n")
	builder.WriteString("<h1>Bookmarks Menu</h1>\n")

	builder.WriteString("<dl><p><dt><h3>Autogenerated Bookmarks</h3>\n")
	builder.WriteString("<dl><p>\n")
	for shortcut, link := range bookmarks {
		builder.WriteString("  <dt><a href=\"https://")
		builder.WriteString(link)
		builder.WriteString("\" shortcuturl=\"")
		builder.WriteString(shortcut)
		builder.WriteString("\">")
		builder.WriteString(shortcut)
		builder.WriteString("</a>\n")
	}
	builder.WriteString("</dl></dl>")

	return builder.String()
}
